### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by wrt54g**
I added dependabot for actions

### CODE REVIEW

**Comment by claha** [comment]
Thanks! Please just fix the yamllint complaint :)

**Comment by wrt54g** [comment]
@claha How? I don't see any issues in this.

**Comment by claha** [comment]
@wrt54g Here https://github.com/custom-components/sensor.avanza_stock/runs/7202956724?check_suite_focus=true

yamllint.................................................................Failed
- hook id: yamllint
- exit code: 2
Warning: [document-start] missing document start "---"

**Comment by claha** [comment]
Looks perfect!

**Pull request merged**
